Repository spryker/git-hook, pull requests merged in 2022-09, with the labels that each got.

#60 FRW-332 Change min PHP version to 7.4
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: merge-only, ready-for-release

#61 PHP 8.1
  .github/workflows/ci.yml
Labels: merge-only

#57 FRW-19 Updated symfony packages to v6
  composer.json
Labels: improvement, merge-only

#62 PHPStan level 8
  README.md
  composer.json
  phpstan.neon
  src/GitHook/Command/FileCommand/PreCommit/PhpStanCheckCommand.php
  src/GitHook/Composer/Scripts/HookInstaller.php
  src/GitHook/Config/ConfigLoader.php
  src/GitHook/Config/GitHookConfig.php
  src/GitHook/Helper/BranchHelper.php
  src/GitHook/Helper/CommittedFilesHelper.php
Labels: improvement, merge-only
